export const FOLDER_CONTEXT_MENU_ID = 'FOLDER_CONTEXT_MENU_ID';

export const NOTE_CONTEXT_MENU_ID = 'NOTE_CONTEXT_MENU_ID';
export const NOTE_CONTEXT_MENU_EL_CLASSNAME = 'NOTE_CONTEXT_MENU_EL_CLASSNAME';

export const USER_CONTEXT_MENU_ID = 'USER_CONTEXT_MENU_ID';
export const USER_CONTEXT_MENU_EL_CLASSNAME = 'USER_CONTEXT_MENU_EL_CLASSNAME';